language: python
sudo: false
python:
  - "2.7"
env:
  global:
    OUTPUT=www
    LIB_COPY=filelist.txt
script:
  true
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  mkdir -p ${OUTPUT} &&
  find . -not -path "*.git/*" -not -path "*${OUTPUT}/*" -not -path "*mvn-repo/*" -type f -not -name "*.py" -not -name "*.tmpl" -not -name "${LIB_COPY}" -not -name ".*" > "${LIB_COPY}" &&
  rsync -av . "${OUTPUT}" --files-from "${LIB_COPY}" &&
  pip install --upgrade pip python-dateutil ghp-import &&
  ./create_page.py --documents content.json --template index.tmpl --out ${OUTPUT}/index.html &&
  ghp-import -n ${OUTPUT} &&
  git push -qf "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" gh-pages
notifications:
  email:
    on_success: never
