name: Python Build

on:
  push:
    branches:
      - master

jobs:
  ci_pipeline:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']
    env:
      OUTPUT: www
      LIB_COPY: filelist.txt
      NO_DEFAULT: 1
      PUBLISH: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Cache python modules
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: |
        make install

    - name: Build
      run: |
        make create
